version: '3.8'

services:
  vite-app:
    build: .
    container_name: vite-app
    ports:
      - "8080:8080"  # 映射容器的 8080 端口到主机的 8080 端口
    volumes:
      - ./dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    restart: always
